### ISSUE TITLE
Talbot's Chainsaw

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/codex-of-the-damned#14]
what mandatory what optional https://groups.google.com/forum/#!msg/rec.games.trading-cards.jyhad/eB1gNn8l3cU/FBBJ6DM8MEUJ

**Comment by lionel-panhaleux** [comment]
Thanks ! For future issues, can you post them on the [KRCG repository](https://github.com/lionel-panhaleux/krcg) ? I know it's a bit confusing, but rulings are updated there, not on the codex.

**Comment by lionel-panhaleux** [comment]
I think the updated official card text if clear on this one: "The bearer gets 1 press (mandatory)".
This was not the case back in the days. If that seems all right with you, I'll just close the issue without adding a ruling.
