### ISSUE TITLE
Lorrie Dunsirn add strike and press

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/codex-of-the-damned#15]
i tru find answer in vekn and google group but fail,but i give you what find from fb 
![image](https://user-images.githubusercontent.com/63711685/80272891-d351ea00-86cd-11ea-8f74-a92f79e2169a.png)

![image](https://user-images.githubusercontent.com/63711685/80272906-f2507c00-86cd-11ea-961d-4eba82176e66.png)

maybe you can find

**Comment by lionel-panhaleux** [comment]
I think these would do https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/s_At5syL66k/1eGsxyhDn1YJ https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/s_At5syL66k/bCvu2ks001gJ

**Comment by lionel-panhaleux** [comment]
Added @ https://github.com/lionel-panhaleux/krcg/commit/842e82d9d9fb4d1b0bf4585ac41d791e1b9b6223
