### ISSUE TITLE
Translation in other languages

### ISSUE THREAD

**Issue by lionel-panhaleux** [lionel-panhaleux/codex-of-the-damned#2]
French, Spanish, Portugese translations would make the site more accessible to new players. Also, card images and texts in these languages should be used.

**Comment by Spigushe** [comment]
I can help a bit in translating into French

**Comment by lionel-panhaleux** [comment]
Oh thanks @Spigushe that would be great ! I'm not really sure how to organise this files-wise.

Having a backend generating the HTML files would sure help (automatic translation based on browser preference, with maybe an opt-in to choose the language), but that's a big change, would you be up for it ? That could also help with og:image meta headers.

For now we can just have an `fr` folder containing the same folder structure than the current one, and add a nice link to switch language on top or bottom of the page, editing all the pages to add the link would be a bit time-consuming, but not complicated.

How do you propose to tackle the issue ?

**Comment by Spigushe** [comment]
Hi @lionel-panhaleux ,

> Having a backend generating the HTML files would sure help (automatic translation based on browser preference, with maybe an opt-in to choose the language), but that's a big change, would you be up for it ? That could also help with og:image meta headers.
I'm not sure what you are looking for but if I can help, I'll help

> For now we can just have an `fr` folder containing the same folder structure than the current one, and add a nice link to switch language on top or bottom of the page, editing all the pages to add the link would be a bit time-consuming, but not complicated.
It can be a good solution for the time being

> How do you propose to tackle the issue ?
We can work with pulling request as I translate each html file

**Comment by lionel-panhaleux** [comment]
Well, that looks good to me ☺︎ Please fell free to PR

**Comment by lionel-panhaleux** [comment]
Thanks for all the hard work @Spigushe !
I made some modifications for packaging and better routing, all changes are merged.

I tried another way to use translations that I feel could be easier for translators, using `{% trans %}` directives with the `trimmed` parameter, which allows us to put links and spans as variables. Check the root `index.html` for an example and tell me what you think.

All in all I didn't change much. For now, I commented out the language switch flags in the header, to activate it only once the French translation is over - you can just uncomment that part if it's easier for you to work on.

You should now be able to focus on translation by starting a new branch from this fresh master 😉

**Comment by lionel-panhaleux** [comment]
French translation is now in beta, soon to be online. Let's open separated tickets for subsequent languages.
In terms of geographic usage, Spanish should come first, potentially followed by Polish and Portuguese.
