### ISSUE TITLE
Links consistency

### ISSUE THREAD

**Issue by Spigushe** [lionel-panhaleux/codex-of-the-damned#24]
il y a pas `%(sce)s` dans ce texte ?

_Originally posted by @Spigushe in https://github.com/lionel-panhaleux/codex-of-the-damned/pull/23#r503312941_

**Comment by lionel-panhaleux** [comment]
I renamed the issue.

Links to the `strategy` sections are not uniform. Some text in `archetypes` or `best-cards` will link to specific notions like `bruise`, `combat ends` and such, others will not provide a link at all. It would be nice for the whole site to be consistent, one way or the other.

For now, the only notion properly linked is the `A&B` reference.

**Comment by lionel-panhaleux** [comment]
Made a pass. Should be far more consistent now
