### ISSUE TITLE
Errors/Clarifications/Omitted Cards in Strategy Pages

### ISSUE THREAD

**Issue by Yomyael** [lionel-panhaleux/codex-of-the-damned#3]
Fundamentals:

Maybe include Lost in Translation in the list of bounces (disciplineless, but only against younger vampires or allies).
Block "Damage dealing votes" notes for Parity Shift that it can only be played against Methuselahs with less pool, should be "more pool" instead.
Ponticulus should maybe be mentioned within the "Permanent intercept cards" block, as the Ponticulus can be locked to give a Tremere +1 intercept.

Combat:

Maybe clarify that Obedience does not require a block (thus can be played after a succesfull rush on the reacting vampire).
In the block "How to deal with S:CE" maybe remove the reference to Immortal Grapple being the best counter, this is debatable. Also, Sanguine Entrapment as something preventing S:CE should be mentioned.
I don't think The Kiss of Ra should be added in the combat section, since it cannot act as a deterrent against combat decks, but more against blocks.

**Comment by lionel-panhaleux** [comment]
Thank a lot for the feedback ! I'll make sure to update soon
