### ISSUE TITLE
Add a "go to rulings" button on card display

### ISSUE THREAD

**Issue by Spigushe** [lionel-panhaleux/codex-of-the-damned#42]
Add a button `Go to rulings` when cards are displayed after a click on its name.

**Question:** Would this behaviour be considered by default when the `media` is a `screen` ?

**Comment by lionel-panhaleux** [comment]
A fine idea, PR welcome !

**Comment by Spigushe** [comment]
#46 
You just need to add a style to your liking

**Comment by lionel-panhaleux** [comment]
Thanks for the contribution! Great improvement thanks to you ☺︎
